### PR TITLE
This PR fixes the FlatButton to TextButton 

### PR DESCRIPTION
**Pull request by shimiuh**
This PR fixes the FlatButton to TextButton, and upgrades flutter and gradle

### CODE REVIEW

**Comment by campio97** [comment]
Please merge

**Comment by phantomlinux** [comment]
i tried to use this PR, but default got error like value isn't defined etc. etc.

**Comment by campio97** [comment]
I think he changed in "selectedValue"

**Comment by Tchoupinax** [comment]
Hello,
we should work on this PR to keep compatibility for future dev as this module is great. :)

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.

**Pull request closed without merging**
