### PR TITLE
Null safety

### PR DESCRIPTION
**Pull request by iktakahiro**
1. I've fixed syntax errors using the migration tool
2. I've fixed some failure tests

### CODE REVIEW

**Comment by SergeyMiracle** [comment]
Is there any way to merge this PR? @davigmacode

**Comment by alr2413** [comment]
ping @davigmacode.

**Comment by RicardoRB** [comment]
Another ping @davigmacode

**Comment by letsfire** [comment]
Another ping @davigmacode

**Comment by SergeyMiracle** [comment]
if author is no longer maintaining maybe someone can take over the package?

**Comment by RicardoRB** [comment]
One ping more @davigmacode

**Comment by alr2413** [comment]
Another ping @davigmacode

**Comment by herman-the-worm** [comment]
@pblinux

**Comment by herman-the-worm** [comment]
@davigmacode ping

**Comment by webtransplatform** [comment]
@davigmacode ping

**Comment by marcoberetta96** [comment]
ping @davigmacode

**Comment by SergeyMiracle** [comment]
no point in 'ping'
someone should make a fork
someone who wants and can maintain package

**Comment by akbarpulatov** [comment]
I forked and uploaded to pub.dev as awesome_select. You can now contribute to https://github.com/akbarpulatov/flutter_smart_select. Thank you! 
PS: I merged this PR. 
Credentials: @iktakahiro
Further PRs are appreciated))

**Comment by this-is-allan** [comment]
Another ping @davigmacode

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by vasilich6107** [comment]
@this-is-allan 
@SergeyMiracle
@iktakahiro 
@marcoberetta96 
@herman-the-worm 
@alr2413 
@RicardoRB 

this PR unfortunately does not have proper null safety migration. 
I forked and fixed the issues in https://pub.dev/packages/flutter_awesome_select

**Comment by RicardoRB** [comment]
> @this-is-allan 
> 
> @SergeyMiracle
> 
> @iktakahiro 
> 
> @marcoberetta96 
> 
> @herman-the-worm 
> 
> @alr2413 
> 
> @RicardoRB 
> 
> 
> 
> this PR unfortunately does not have proper null safety migration. 
> 
> I forked and fixed the issues in https://pub.dev/packages/flutter_awesome_select

Hey thank you for your work, but spamming to everyone everywhere, multiple times, I believe isn't the best approach to let the people know it.

**Comment by vasilich6107** [comment]
May be)
But how they would know if not?)
I’m not considering this is as spam. I would rather say that it is targeted information that could be very helpful in case if users still want to use this package.

**Comment by akbarpulatov** [comment]
It is already fixed in https://github.com/akbarpulatov/flutter_smart_select

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.

**Pull request closed without merging**
