### PR TITLE
add option for providing custom header actions

### PR DESCRIPTION
**Pull request by SvenSchoene**
In our project we need the ability to provide custom actions to our bottom sheet modals. This is probably the only feature that this awesome library did not implement, so I felt like contributing my attempt at the implementation of that feature.

The code is simple enough. However, you have a better overview over the codebase and know what I missed and/or didn't take into consideration.

Feel free to point out any changes you feel like I should be making.  
Or, alternatively I have no issues with you closing this PR and doing your own implementation.  
Obviously, if you feel like this feature shouldn't be supported at all, you're also free to reject this. It's just that we really need this ability to customize the actions there.

Here's one example for how we're using it:

smart_select_header

Thanks for the great library, by the way. You really took into account nearly every possible use case!

[EDIT]  
There have been some auto-format changes. To be clear, the only relevant changes are:

* `modal_header.dart`: 84-92 + 105
* `modal_config.dart`: 31-33 + 55
* `modal_theme.dart`: 52-54 + 65

### CODE REVIEW

**Comment by SvenSchoene** [comment]
I understand that library developers have lots of other stuff to do. But it's been 16 days, and I'd love to get some feedback on this (and ideally have the chance of getting this merged). @davigmacode

**Comment by alr2413** [comment]
Ping @davigmacode

Please if everything is okay, merge it.
Thanks.

**Comment by davigmacode** [comment]
Hi @SvenSchoene @alr2413 

I am very sorry, I have been very busy with my main job in the last few months, and may still continue in the next 2 months.

I really appreciate your time contributing to the development of this package, but in this case I think the current version covers what you need, please check the issue #4

You can also check the upcoming version in the [v4 branch](https://github.com/davigmacode/flutter_smart_select/tree/v4.0.0) along with the [examples](https://github.com/davigmacode/flutter_smart_select/tree/v4.0.0/example), it comes with a lot of improvements (including custom header and footer), it's just that I haven't published it yet because there are features that haven't been completed and I haven't had the chance to continue it.

These are some of the features that are still under development
- Fully support async load choice items with custom search
- Choice items pagination (pull to refresh and pull to load more)

**Comment by SvenSchoene** [comment]
Hey @davigmacode ,

No worries, I appreciate the package, so that's good enough! :) 

I looked at the v4 branch and it indeed looks like I could pass a different `header` to `S2Modal`. That's cool, that would help!

I'll also take a look at the confirmation builder again. I'm not sure why I dismissed that the first time I looked at it. 

Ultimately I believe providing the option for custom header actions instead of only (very well-picked!) predefined ones is a cool feature nonetheless -- especially if it's as simple / "cheap" to implement as here. I understand if one decides this isn't in the scope of this package, though, or it adds more complexity in some other ways that I'm simply not aware of, which might make the cost-benefit-calculation not look as good anymore.

And, again, it looks like with confirmation builder I can do exactly what I want in this instance anyway. 

Anyway, good luck with your job and I'm looking forward to v4 at some point! 👍

**Pull request closed without merging**
